name = "pearl"
version = "2.0.0"

description = "An Erlang lexer and syntax highlighter for Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "GearsDatapacks", repo = "pearl" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/GearsDatapacks" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
splitter = ">= 1.0.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
houdini = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
birdie = ">= 1.4.0 and < 2.0.0"
